config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#index"
  apipie
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :guests, only: [:show]
  resources :categories, only: :index
  resources :requests, only: :create

  resources :reviews do
    delete :delete_attachment, on: :member
    get :update_favourite
    get :get_score
    get :update_status
  end

  scope :users do
    resources :groups, only: [:index, :create, :update, :destroy, :show] do
      post :show, on: :member
    end
  end
  get 'groups/search'
  get 'users/index'
  patch 'users/update'
  get 'users/remove_avatar'
  get 'users/delete_user'
  get 'users/settings'
  patch 'users/update'
  post 'upload', to: 'file_uploads#upload'
  patch :update_categories_status, to: 'categories#update_categories_status'
  get :homepage, to: 'reviews#homepage'
  get :edit_new, to: 'groups#edit_new'
  get :create_review, to: 'guests#create_review'
  get :show_map, to: 'reviews#show_map'
  post :homepage, to: 'reviews#homepage'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      mount_devise_token_auth_for "User", at: "/users", controllers: {
        sessions: "api/v1/sessions",
        passwords: "api/v1/passwords",
        registrations: "api/v1/registrations"
      }
      resources :reviews, only: [:create, :index, :update] do
        post :create_review_with_num
      end
      resources :groups, only: [:index, :create, :update, :destroy]
      resources :categories, only: :index
      resources :users, only: :update do
        post :change_password
      end
      resources :filters, only: :index
    end
  end

end

app/models/group.rb
class Group < ApplicationRecord
  include Discard::Model
  default_scope -> { kept }

  has_and_belongs_to_many :reviews
  belongs_to :user

  accepts_nested_attributes_for :reviews

end

app/controllers/api/v1/groups_controller.rb
module Api
  module V1
    class GroupsController < Api::V1::ApiController
      before_action :set_group, only: [:update, :destroy ]

      api :GET, "groups", "Get a list of all available groups"

      example <<-EOS
        
      Status Codes with Response
      200: {
        "groups": [
        {
            "id": 31,
            "name": "Test",
            "created_at": "2022-12-06T14:33:23.328Z",
            "updated_at": "2022-12-06T14:33:23.328Z",
            "user_id": 2,
            "discarded_at": null
          }
        ]
      }
      EOS

      def index
        pagy, groups = pagy(current_user.groups)
        render json: groups, meta: pagy_meta(pagy), each_serializer: GroupSerializer, adapter: :json
      end

      api :POST, "groups", "Create a new group"

      def create
        group = current_user.groups.new(group_params)
        if group.save
          group.review_ids = params[:reviews] if params[:reviews].present?
          render json: group, each_serializer: GroupSerializer, adapter: :json
        else
          render_error(422, "Group didn't created successfully")
        end
      end

      api :PUT, "groups", "Update a group"

      def update
        @group.review_ids = params[:reviews] if params[:reviews].present?
        if @group.update(group_params)
          render json: @group, each_serializer: GroupSerializer, adapter: :json
        else
          render_error(422, "Group didn't updated")
        end
      end

      api :DELETE, "groups", "Delete a group"

      def destroy
        if @group.discard
          render_message("Group deleted successfully!")
        else
          render_error(422, "Group cannot be deleted")
        end
      end

      private
      def set_group
        @group = current_user.groups.find(params[:id])
      end

      def group_params
        params.require(:group).permit(:name)
      end

    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups.all
  end

  def show
    @group = current_user.groups.find(params[:id])
    reviews = current_user.groups.find(params[:id]).reviews
    @pagy, @reviews = pagy_countless(reviews)
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def edit_new
    if params[:id].present? #case of edit
      @group = current_user.groups.find(params[:id])
      @selected_reviews = @group.reviews
      @reviews = current_user.reviews.all_except(@selected_reviews)
    else
      #case of new
      @reviews = current_user.reviews
      @group = current_user.groups.new
    end
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      @group.review_ids = params[:group][:reviews] if params[:group][:reviews].present?
      flash[:notice] = "Group created successfully!"
    else
      flash[:alert] = "Error in creating group!"
    end
    redirect_to groups_path
  end

  def update
    @group = current_user.groups.find(params[:id])
    @group.review_ids = params[:group][:reviews] if params[:group][:reviews].present?
    if @group.update(group_params)
      flash[:notice] = "Group updated successfully!"
    else
      flash[:alert] = "Error in updating group!"
    end
    redirect_to groups_path
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    if @group.discard
      flash[:notice] = "Group deleted successfully!"
    else
      flash[:alert] = "Group cannot be deleted"
    end
    redirect_to groups_path, status: :see_other
  end

  def group_params
    params.require(:group).permit(:name)
  end

end

app/views/groups/_edit_group_modal.html.erb
<!--Edit group Modal -->
<div class="modal fade" id="edit-group-modal" tabindex="-1" aria-labelledby="edit-group-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="edit-group-modal-label">Add Folder</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_for @group, url: groups_path do |group_frm| %>
        <div class="modal-body">
          <div class="mb-4">
            <%= group_frm.label :name, "Name", class: "form-label" %>
            <%= group_frm.text_field :name, class: "form-control input-height", placeholder: "Name your folder", type: "text" %>
          </div>
          <div class="mb-4">
            <%= group_frm.label "Add Reviews", class: "form-label" %>
            <%#= group_frm.text_field :search, class: "form-control input-height", placeholder: "Search for reviews", type: "text", data: { "action": "keyup->group#search" } %>
          </div>
          <div>
            <%= render "modal_review_cards", reviews: @reviews %>
          </div>
        </div>
        <div class="modal-footer justify-content-between">
          <div>
          <button type="button" class="btn white modal-cancel" data-bs-dismiss="modal">Cancel</button>
          <%#= link_to "Delete", group_path(group), data: { turbo_method: :delete }, class: "btn delete" %>
          </div>
            <%= group_frm.submit "Save Changes", class: 'save-changes', "data-action": "click->group#reviews" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/_group_cards.html.erb
<div class="content_area" data-simplebar>
  <div class="content_wrap pb_100">
    <div class="container mt_30">
      <div class="tab-content">
        <!--All grid groups here -->
        <div class="tab-pane fade show active" id="grid_layout1" role="tabpanel">
          <div class="row mt-3 g-5">
            <%= render partial: 'single_group_card' , collection: groups, as: :group %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/_modal.html.erb
<!--Edit group Modal -->
<div class="modal fade" id="groupModal" tabindex="-1" aria-labelledby="group-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="group-modal-label">Add Folder</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with model: group do |group_frm| %>
        <div class="modal-body">
          <div class="mb-4">
            <%= group_frm.label :name, "Name", class: "form-label" %>
            <%= group_frm.text_field :name, class: "form-control input-height", placeholder: "Name your folder", type: "text" %>
          </div>
          <div class="mb-4">
            <%= group_frm.label "Add Reviews", class: "form-label" %>
            <input class="form-control input-height" placeholder= "Search for reviews" type= "text" data-action="keyup->group#searchRequest" data-group-target="searchField" >
          </div>
          <div id="modalSearchReviewsAppend"></div>
          <div id="modalReviewsAppend">
            <% if @selected_reviews.present? %>
              <%= render "modal_review_cards", reviews: @reviews , selected_reviews: @selected_reviews  %>
            <% else %>
              <%= render "modal_review_cards", reviews: @reviews %>
            <% end %>
          </div>
        </div>
        <div class="modal-footer justify-content-between">
          <div>
          <button type="button" class="btn white modal-cancel" data-bs-dismiss="modal">Cancel</button>
          </div>
            <%= group_frm.submit "Save Changes", class: 'save-changes' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/_modal_review_cards.html.erb
<div class="content_area">
  <div class="content_wrap pb_10">
    <div class="container mt_30">
      <div class="tab-content">
        <!--All grid card here -->
        <div class="tab-pane fade show active" id="grid_layout1" role="tabpanel">
          <% if @selected_reviews.present? %>
            <div class="row g-5 mb-5 outer-review-card-select">
              <%= render partial: 'modal_single_review', collection: selected_reviews, as: :review %>
            </div>
            <hr>
          <% end %>
          <div class="row g-5">
            <%= render partial: 'modal_single_review', collection: reviews, as: :review %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/_modal_single_review.html.erb
<!-- single card -->
<div class="col-lg-3 col-md-6" data-controller="review-search" data-review-search-name-value = <%= review.name %>>
  <div class="card small-card-review selected" data-action="click->group#cardSelect">
    <input type="checkbox" hidden="true" value=<%= review.id %> name="group[reviews][]">
    <div class="card-header p-0 border-0 position-relative">
      <% if review.images.present? %>
        <div data-controller = "carousel-loader" class="owl-carousel owl-theme card_carousel">
          <% review.images[..5].each do |image| %>
            <div class="item"><%= image_tag(image) %></div>
          <% end %>
        </div>
      <% else %>
        <div class="image-placeholder item"><%= image_tag("template/card-placeholder.svg") %></div>
      <% end %>
    </div>
    <div class="small-card-body">
      <div class="small-review-top">
        <p class="small-name"><%= review.name %></p>
        <% if review.average_score.present? %>
          <p class="small-rating">
            <%= image_tag("template/star.svg") if review.average_score? %>
            <span><%= review.average_score %></span>
          </p>
        <% else %>
          <span class='review_btn small-review-card'><%= review.to_try ? "Wishlist" : "Review" %> </span>
        <% end %>
      </div>
      <% if review.state.present? and review.country.present? %>
        <div class="small-review-state"><%= review.state %>, <%= review.country %></div>
      <% else %>
        <div class="small-review-state"><%= review.date.strftime("%b %e, %Y") if review.date? %></div>
      <% end %>
      <div class="d-flex align-items-center">
        <% if review.sub_category_id.present? %>
        <span class="cuisine-tag small-review-cuisine">
         <%= review.sub_category.name %>
        </span>
        <% end %>
        <span class=""><%= image_tag(review.shareable ? "template/add.png" : "template/lock.svg") %></span>
      </div>
    </div>
  </div>
</div>

app/views/groups/_single_group_card.html.erb
<div class="col-lg-3 col-md-6">
  <div class="group-card">
    <%= link_to group_path(group), class: "group-link" do %>
      <% if group.reviews.pluck(:images).flatten.present? %>
        <% if group.reviews.pluck(:images).flatten.count == 1 %>
          <div class="col-12">
            <img class="group-image" src=<%= group.reviews.pluck(:images).flatten.first %>>
          </div>
        <% elsif group.reviews.pluck(:images).flatten.count == 2 %>
          <div class="two-image-thumbnail row gx-1">
            <div class="col-6">
              <img class="group-half-thumbnail" src=<%= group.reviews.pluck(:images).flatten.first %>>
            </div>
            <div class="col-6">
              <img class="group-half-thumbnail" src=<%= group.reviews.pluck(:images).flatten.second %>>
            </div>
          </div>
        <% else %>
          <div class="three-image-thumbnail row gx-1">
            <div class="col-8">
              <img class="group-half-thumbnail" src=<%= group.reviews.pluck(:images).flatten.first %>>
            </div>
            <div class="col-4">
              <div class="col-12 top mb-1">
                <img class="group-quarter-thumbnail" src=<%= group.reviews.pluck(:images).flatten.second %>>
              </div>
              <div class="col-12 bottom">
                <img class="group-quarter-thumbnail" src=<%= group.reviews.pluck(:images).flatten.third %>>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="col-12">
          <%= image_tag("template/card-placeholder.svg", class: "group-image") %>
        </div>
      <% end %>
      <h3 class="mx-2 mt-2"><%= group.name %></h3>
      <span class="text mx-2"><%= group.reviews.count %> Folders</span>
    <% end %>
    <span class="group-pen-icon" data-groupId="<%= group.id %>" data-bs-toggle="modal" data-bs-target="#exampleModal" data-action="click->group#newRequest">
      <%= image_tag("template/edit.svg") %>
    </span>
  </div>
</div>

app/views/groups/edit_new.js.erb
$("#groupModalAppend").html('<%=j render "modal", group: @group %>')
$('#groupModal').modal('toggle');

app/views/groups/index.html.erb
<main class="container overflow-hidden" data-controller="group" data-group-search-value="<%= groups_search_path %>" data-group-newgroup-value="<%= edit_new_path %>">
  <%= render "shared/profile_image" %>
  <span class="user-name d-flex justify-content-center profile-name mt-3"><%= current_user.username %></span>
  <div class="row justify-content-center pt_30">
    <button class='col-lg-2 col-md-3 col-8 mt-3 mt-md-0 btn mx-2 grp-btn' data-bs-target="#groupModal" data-action="click->group#newRequest">
      <%= image_tag("template/plus.svg") %><span>Add New</span>
    </button>
  </div>
  <%= render "group_cards", groups: @groups %>
  <div id="groupModalAppend"></div>
</main>

app/views/groups/new.js.erb
$("#groupModalAppend").html('<%=j render "modal" %>')
$('#groupModal').modal('toggle');

app/views/groups/search.js.erb
$("#modalReviewsAppend").html('<%=j render "modal_review_cards", reviews: @reviews %>')

app/views/groups/show.html.erb
<main class="container overflow-hidden" data-controller="group" data-group-search-value="<%= groups_search_path %>" data-group-newgroup-value="<%= edit_new_path %>">
  <%= link_to groups_path do %>
    <span class="back grp-back"><%= image_tag("template/left-arrow.svg")%></span>
  <% end %>
  <%= render "shared/profile_image" %>
  <span class="user-name d-flex justify-content-center profile-name mt-3"><%= @group.name.titleize %></span>
  <div class="row justify-content-center pt_30" data-controller="guest">
    <button type="button" class="col-lg-1 col-md-3 col-8 grp-btn share-grp-btn mx-2" data-bs-toggle="modal" data-bs-target="#shareModal" data-action="click->guest#addLinkField">
      <%= image_tag("template/share.svg") %><span class="mx-2">Share</span>
    </button>
    <button class='col-lg-1 col-md-3 col-8 mt-3 mt-md-0 grp-btn edit-grp-btn mx-2' data-groupId="<%= @group.id %>" data-action="click->group#newRequest">
      <%= image_tag("template/edit.svg") %><span class="mx-2">Edit</span>
    </button>
    <%= link_to "Delete", group_path(@group), data: { turbo_method: :delete }, class: "grp-btn delete col-lg-1 col-md-3 col-8 mt-3 mt-md-0 btn mx-2" %>
    <%= render "shared/share_modal" %>
  </div>
  <%= render "new_homepage/review_cards", reviews: @reviews, pagy: @pagy %>
  <div id="groupModalAppend"></div>
</main>

app/views/groups/show.turbo_stream.erb
<%= render 'shared/review_cards', reviews: @reviews, pagy: @pagy %>