config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#index"
  apipie
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :guests, only: [:show]
  resources :categories, only: :index
  resources :requests, only: :create

  resources :reviews do
    delete :delete_attachment, on: :member
    get :update_favourite
    get :get_score
    get :update_status
  end

  scope :users do
    resources :groups, only: [:index, :create, :update, :destroy, :show] do
      post :show, on: :member
    end
  end
  get 'groups/search'
  get 'users/index'
  patch 'users/update'
  get 'users/remove_avatar'
  get 'users/delete_user'
  get 'users/settings'
  patch 'users/update'
  post 'upload', to: 'file_uploads#upload'
  patch :update_categories_status, to: 'categories#update_categories_status'
  get :homepage, to: 'reviews#homepage'
  get :edit_new, to: 'groups#edit_new'
  get :create_review, to: 'guests#create_review'
  get :show_map, to: 'reviews#show_map'
  post :homepage, to: 'reviews#homepage'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      mount_devise_token_auth_for "User", at: "/users", controllers: {
        sessions: "api/v1/sessions",
        passwords: "api/v1/passwords",
        registrations: "api/v1/registrations"
      }
      resources :reviews, only: [:create, :index, :update] do
        post :create_review_with_num
      end
      resources :groups, only: [:index, :create, :update, :destroy]
      resources :categories, only: :index
      resources :users, only: :update do
        post :change_password
      end
      resources :filters, only: :index
    end
  end

end

app/views/shared/_filter_modal.html.erb
<!--filter modal-->
<div class="modal fade" id="filterModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header" style="height: 72px; padding: 20px 24px;">
        <h5 class="modal-title filter-h" id="filterModalLabel">Filters</h5>
        <span type="button" class="filter-close" data-bs-dismiss="modal" aria-label="Close">x</span>
      </div>
      <div class="modal-body" style="background: #FBFBFE;">
        <% if current_user.second_view.present? %>
          <div class="card cuisine-card-h mb-5">
            <div class="d-flex justify-content-between p-4">
              <span class="cuisine-font cuisine-h">Sort</span>
            </div>
            <div class="tag-card-h overflow-auto pb-3">
              <%= f.hidden_field :score, value: params[:score], 'data-filter-target': "scoreFilter" %>
              <%= select_tag :score, options_for_select([["Newest", "recent"], ["Top Rated", "desc"], ["Low Rated", "asc"]], params[:score]), data: { "filter-target": "sortReviews" } %>
            </div>
          </div>
        <% end %>

        <div class="card cuisine-card-h">
          <div class="d-flex justify-content-between p-4">
            <span class="cuisine-font cuisine-h">Location</span><span class="cuisine-font cuisine-clear cursor-pointer" data-action="click->filter#locationClearAll ">X Clear All</span>
          </div>
          <div class="tag-card-h overflow-auto">
            <%= f.hidden_field :location_filter, :value => "#{params[:location_filter]}", 'data-filter-target': "locationFilter" %>
            <% @addresses.each do |address| %>
              <span class="cuisine-badge d-inline-block mb-4 cuisine-font <%= params[:location_filter]&.split(',')&.index(address.titleize).present? ? 'cuisine-select clear-location' : 'cuisine-unselect' %> cursor-pointer" data-action="click->filter#selectLocation"><%= address.titleize %></span>
            <% end %>
          </div>
        </div>
        <div class="card cuisine-card-h mt-5">
          <div class="d-flex justify-content-between p-4">
            <% if params[:category_id].present? && params[:category_id] == "all" %>
              <span class="cuisine-font cuisine-h">Sub Category</span><span class="cuisine-font cuisine-clear cursor-pointer" data-action="click->filter#cuisineClearAll ">X Clear All</span>
            <% else %>
              <span class="cuisine-font cuisine-h"><%= Category.find(params[:category_id]).sub_category_title if params[:category_id].present? %></span><span class="cuisine-font cuisine-clear cursor-pointer" data-action="click->filter#cuisineClearAll ">X Clear All</span>
            <% end %>
          </div>
          <div class="tag-card-h overflow-auto">
            <%= f.hidden_field :cuisines_filter, :value => "#{params[:cuisines_filter]}", 'data-filter-target': "cuisinesFilter" %>
            <%= f.hidden_field :category_id, value: @curr_category.id if @curr_category != "all" %>
            <% cuisines.each do |cuisine| %>
              <% if cuisine.present? %>
                <span class="cuisine-badge d-inline-block mb-4 cuisine-font <%= params[:cuisines_filter]&.split(',')&.index(cuisine.titleize).present? ? 'cuisine-select clear-cuisine' : 'cuisine-unselect' %> cursor-pointer" data-action="click->filter#selectCuisine"><%= cuisine.titleize %></span>
              <% end %>
            <% end %>
          </div>
        </div>

        <div class="card mt-5">
          <div class="d-flex justify-content-between p-4">
            <span class="cuisine-font cuisine-h">Tags</span><span class="cuisine-font cuisine-clear cursor-pointer" data-action="click->filter#TagClearAll">X Clear All</span>
          </div>
          <div class="tag-card-h overflow-auto">
            <%= f.hidden_field :tags_filter, :value => "#{params[:tags_filter]}", 'data-filter-target': "tagsFilter" %>
            <% tags.each do |tag| %>
              <span class="mb-4 cuisine-badge d-inline-block cuisine-font <%= params[:tags_filter]&.split(',')&.index(tag.titleize).present? ? 'cuisine-select clear-tag' : 'cuisine-unselect' %> cursor-pointer" data-action="click->filter#selectTag"><%= tag.titleize %></span>
            <% end %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="d-flex justify-content-between w-100">
          <button type="button" class="filter-btn filter-cancel" data-bs-dismiss="modal" style=" margin-left: unset;">Cancel</button>
          <span type="button" class="filter-btn filter-apply" data-filter-target="applyBtn" data-action="click->filter#applyFilter">Apply</span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<% if flash.notice || flash.alert %>
  <div class="col-lg-8 col-12 flash-msg">
    <div class="alert <%= flash.notice ? 'alert-primary' : 'alert-danger' %> alert-dismissible fade show" role="alert">
      <%= flash.notice || flash.alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/shared/_form.html.erb
<main class="position-relative">
  <span class="back" data-controller="guest" data-action="click->guest#back"><%= image_tag("template/left-arrow.svg") %></span>
  <div class="add_review_area">
    <!-- page header start-->
    <div class="add_review_area_header sticky-top pt_20">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <h2 class="title">Add Review</h2>

            <!-- add review nav start -->
            <ul class="nav nav-pills justify-content-between" id="add-restaurant-review-nav">
              <li class="nav-item">
                <a href="#category_area" class="active nav-link">Category</a>
              </li>

              <li class="nav-item">
                <a href="#review_area" class="nav-link">Description</a>
              </li>

              <li class="nav-item">
                <a href="#photo_area" class="nav-link">Photos</a>
              </li>
              <% if @curr_category.address? %>
                <li class="nav-item">
                  <a href="#localization_area" class="nav-link">Localization</a>
                </li>
              <% end %>

              <% if @curr_category.address? %>
                <li class="nav-item">
                  <a href="#favourite_dishes_area" class="nav-link">Highlights</a>
                </li>
              <% end %>

              <li class="nav-item">
                <a href="#tags_area" class="nav-link">Tags</a>
              </li>

            </ul>
            <!-- add review nav end -->
          </div>
        </div>
      </div>
    </div>
    <!-- page header end-->

    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6">
          <%= form_for review, html: {'data-turbo': "false", 'class': "review-form" } do |form| %>
            <div data-controller="places"
                 data-action="google-maps-callback@window->places#initMap" data-places-country-value='["us"]'
                 data-places-latitude-value="<%= review.latitude %>"
                 data-places-longitude-value="<%= review.longitude %>"
                 data-places-place-id-value="<%= review.place_id %>">

              <!-- category area -->
              <div class="category_area pt_35" id="category_area">
                <%= render 'reviews/category', review: review, f: form %>
              </div>

              <!-- review area start -->
              <div class="review_area" id="review_area">
                <%= render 'reviews/review', review: review, f: form, curr_category: @curr_category %>
              </div>

              <!-- photo area start -->
              <div class="photo_area pt_35" id="photo_area">
                <%= render 'reviews/photos', review: review, f: form %>
              </div>

              <!-- localization area start -->
              <% if @curr_category.address? %>
                <div class="localization_area pt_35" id="localization_area">
                  <%= render 'reviews/localization', review: review, f: form %>
                </div>
              <% end %>

              <% if @curr_category.cuisine? %>
                <div class="favourite_dishes_area pt_35" id="favourite_dishes_area">
                  <%= render 'reviews/favourite_dishes', review: review, f: form %>
                </div>
              <% end %>

              <!-- tags area start -->
              <div class="tags_area pt_35" id="tags_area">
                <%= render 'reviews/tags', review: review, f: form %>
              </div>

              <div class="row pt_50 align-items-center">
                <div class="col-3 col-sm-4">
                  <a class="btn white cancel" href="#">Cancel</a>

                  <% if form.object.persisted? %>
                    <button type="button" class="btn delete" data-bs-toggle="modal" data-bs-target="#deleteModal">
                      Delete
                    </button>
                    <!-- Delete Modal -->
                    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content rounded-20">
                          <div class="modal-body bg-white rounded-20">
                            <div class="d-flex justify-content-center align-items-center p-19 logout-heading">
                              Delete Review
                            </div>
                            <div class="d-flex justify-content-center align-items-center mb-5">
                              Are you sure you want to delete review?
                            </div>
                            <div class="d-flex justify-content-evenly pb-5 flex-wrap">
                              <button type="button" class="modal-cancel btn-modal d-flex justify-content-center align-items-center" data-bs-dismiss="modal">Cancel</button>
                              <%= link_to "Delete", review_path(review), data: { turbo: true, turbo_method: :delete }, class: "delete-account btn-modal d-flex justify-content-center align-items-center" %>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
                <div class="col-9 col-sm-8 d-flex justify-content-end">
                  <div class="public_review">
                    <div class="mode-switch d-flex flex-row align-items-center">
                      <%= form.check_box :shareable, id: 'switch' %>
                      <label for="switch"></label>
                    </div>
                    <%= image_tag('template/users.svg', class: 'mr_5') %>
                    <span>Public REVIEW</span>
                  </div>
                  <%= form.submit form.object.persisted? ? "Update Review" : "Add Review", class: 'add-review-btn ml_25' %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/shared/_guest_show_header.html.erb
<div class="row align-items-end pb_50">
  <div class="col-lg-6">
    <h1><%= @review.name %></h1>
    <% if !@review.city.present? %>
      <p class="date">
        <%= @review.date.strftime("%b/%e/%Y") %>
      </p>
    <% end %>
    <ul class="list_group">
      <% if @review.city.present? %>
        <li><%= @review.city %></li>
      <% end %>
      <% if @review.state.present? and @review.country.present? %>
        <li><%= @review.state + ', ' %> <%= @review.country %></li>
      <% end %>
      <li>
        <span>$</span>
        <span>$</span>
        <span>$</span>
        <span>$</span>
      </li>
    </ul>
  </div>
  <div class="col-lg-6 text-end d-none d-lg-block">
    <div class="d-flex align-items-center justify-content-end avatar">
      <div class="d-flex align-items-center justify-content-evenly rating_box">
        <%= image_tag("template/star.svg", class: "w-25") %> <span class="align-items-center d-flex pt-2 rating"><%= @review.average_score %></span>
      </div>

      <% if User.find_by(id: @review.user_id).avatar.attached? %>
        <%= image_tag(User.find_by(id: @review.user_id).avatar, class: 'rounded-circle h-auto') %>
      <% else %>
        <%= image_tag("template/avatarplaceholder.jpg", class: 'rounded-circle h-auto') %>
      <% end %>
      <div>
        <span class="name pl_10"><span class="text-black-50">by</span> <%= User.find_by(id: @review.user_id).first_name %> <%= User.find_by(id: @review.user_id).last_name %></span>
      </div>
    </div>
    <div>
      <a class="btn white" href="#"><%= image_tag("template/check.svg") %><span>Mark To Try</span></a>
      <%= link_to "Write Your Review", "#", class: 'btn' %>
    </div>
  </div>

  <!-- for mobile -->
  <div class="col-12 d-lg-none">
    <div class="d-flex justify-content-between align-items-center pt_30">
      <div class="d-flex align-items-center avatar">
        <% if User.find_by(id: @review.user_id).avatar.attached? %>
          <%= image_tag(User.find_by(id: @review.user_id).avatar, class: 'rounded-circle h-auto') %>
        <% else %>
          <%= image_tag("template/avatarplaceholder.jpg", class: 'rounded-circle h-auto') %>
        <% end %>
        <div class="pl_10">
          <p class="reviewer">Reviewer</p>
          <p class="name"><%= @review.name %></p>
        </div>
      </div>
      <div class="rating_box">
        <p class="rating"><%= image_tag("template/star.svg") %>
          <span><%= @review.average_score %></span></p>
      </div>
    </div>
    <div class="d-flex justify-content-between pt_30">
      <%= link_to "#" %>
      <a class="btn white" href="#"><%= image_tag("template/check.svg") %><span>Mark To Try</span></a>
      <%= link_to "Write Your Review", edit_review_path(@review), class: 'btn' %>
    </div>
  </div>
  <!-- mobile end-->
</div>

app/views/shared/_header.html.erb
<header class="d-flex align-items-center sticky-top">
  <div class="container">
    <div class="row align-items-center">
      <div class="<%= current_user.second_view ? "col-6" : "col-3" %>">
        <%= link_to root_path, class: 'logo', "data-turbo": false do %>
          <%= image_tag("template/fullsite-logo.svg", class: "d-lg-block d-none") %>
          <%= image_tag("template/smallsite-logo.svg", class: "d-lg-none d-block") %>
        <% end %>
      </div>
      <% if !current_user.second_view? %>
        <div class="col-5 col-sm-6 text-center">
          <ul class="menu d-lg-inline-flex align-items-center jutify-content-center d-none d-lg-block">
            <li>
              <%= link_to "All", params[:profile].present? ? users_index_path(category_id: 'all', profile: 'true') : reviews_path(category_id: 'all'), class: "nav_link #{'category-active' if params[:category_id] == 'all' || !params[:category_id].present?}" %>
            </li>
            <% default_categories.each do |category| %>
              <li>
                <%= link_to reviews_path(category_id: category.id), class: "nav_link #{'category-active' if params[:category_id].to_i == category.id}" do %>
                  <!--      TODO will uncomment when S3 will configure-->
                  <%#= show_svg(category.icon) if category.icon.attached? %>
                  <span class="ml_5">
                <%= category.name.titleize %>
                </span>
                  </li>
                <% end %>
            <% end %>
            <% if common_categories.present? %>
              <li class="dropdown-center ml_15">
                <a href="#" id="menu_dropdown" data-bs-toggle="dropdown" aria-expanded="false"><%= image_tag("template/more-horiz.svg") %></a>
                <ul class="dropdown-menu">
                  <% common_categories.each do |category| %>
                    <li>
                      <%= link_to reviews_path(category_id: category.id), class: "dropdown-item #{'active' if params[:category_id].to_i == category.id}" do %>
                        <!--      TODO will uncomment when S3 will configure-->
                        <%#= show_svg(category.icon) if category.icon.attached? %>
                        <span class="ml_5">
                        <%= category.name.titleize %>
                      </span>
                      <% end %>
                    </li>
                  <% end %>
                  <hr class="m-auto">
                  <li><%= link_to "Manage categories", categories_path, class: "dropdown-item" %></li>
                </ul>
              </li>
            <% end %>
          </ul>
          <!-- menu dropdown for mobile -->
          <div class="d-lg-none dropdown menuItemDropdown">
            <%= link_to "Categories", params[:profile].present? ? users_index_path(category_id: 'all', profile: 'true') : reviews_path(category_id: 'all'), "aria-expanded": "false", "data-bs-toggle": "dropdown", class: "nav_link #{'active' if params[:category_id] == 'all' || !params[:category_id].present?} toggler w-auto" %>
            <ul class="dropdown-menu" aria-labelledby="menuItemDropdown">
              <li>
                <%= link_to "All", params[:profile].present? ? users_index_path(category_id: 'all', profile: 'true') : reviews_path(category_id: 'all'), class: "icon" %>
              </li>
              <% all_categories.each do |category| %>
                <li>
                  <%= link_to reviews_path(category_id: category.id), class: "icon" do %>
                  <span class="icon">
                      <!--  TODO will uncomment when S3 will configure-->
                    <%#= show_svg(category.icon) if category.icon.attached? %>
                    </span>
                    <%= category.name %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
      <div class="<%= current_user.second_view ? "col-6" : "col-4 col-sm-3" %> text-end">
        <% if user_signed_in? %>
          <div class="dropdown user d-inline-block">
            <a class="d-inline-flex align-items-center" href="#" id="sessionDropdown" data-bs-toggle="dropdown" aria-expanded="false">
              <p class="name">Hello, <span><%= current_user.username %></span></p>
              <span class="header-img user-img-wrapper">
                      <%= image_tag(current_user.avatar.attached? ? current_user.avatar : "template/avatar_placeholder.jpg") %>
                        </span>
              <%= image_tag("template/bottom-arrow1.png", class: 'arrow') %>
            </a>
            <ul class="dropdown-menu dropdown-w" aria-labelledby="sessionDropdown">
              <li class="cursor-pointer">
                <div class="dropdown-item p-3">
                  <div class="d-flex ">
                      <span class="col-2 user-img-wrapper dropdown-img">
                      <%= image_tag(current_user.avatar.attached? ? current_user.avatar : "template/avatar_placeholder.jpg") %>
                        </span>
                    <div class="d-inline dropdown-info">
                      <span class="d-block user-name"><%= current_user.username %></span>
                      <span class="user-email"><%= current_user.email %></span>
                    </div>
                  </div>
                </div>
              </li>
              <li class="cursor-pointer">
                <%= link_to "My Profile", users_index_path(profile: 'true'), class: "dropdown-item" %>
              </li>
              <li class="cursor-pointer">
                <%= link_to "Groups", groups_path, class: "dropdown-item" %>
              </li>
              <li class="cursor-pointer">
                <%= link_to "Edit Account", edit_user_registration_path, class: "dropdown-item" %>
              </li>
              <li class="cursor-pointer">
                <%= link_to "Settings", users_settings_path, class: "dropdown-item" %>
              </li>
              <li class="dropdown-item pb-3 m-0 pr-2 pl-4 pt-3 cursor-pointer" data-bs-toggle="modal" data-bs-target="#logOutModal">
                <a class="dropdown-item" href="#" onclick="event.preventDefault()">Log Out</a>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</header>

<div class="modal fade" id="logOutModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content rounded-20">
      <div class="modal-body bg-white p-5 rounded-20">
        <div class="d-flex justify-content-center align-items-center p-19 logout-heading">
          Log Out
        </div>
        <div class="d-flex justify-content-center align-items-center">
          Are you sure you want to logout?
        </div>
      </div>
      <div class="d-flex justify-content-evenly pb-5 flex-wrap">
        <a type="button" class="modal-cancel btn-modal d-flex justify-content-center align-items-center" data-bs-dismiss="modal">Cancel</a>
        <%= link_to 'Log Out', destroy_user_session_path, data: { "turbo-method": :delete }, class: 'btn-logout btn-modal d-flex justify-content-center align-items-center' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_list_review_card.html.erb
<!-- single card -->
<div class="mb-4 d-lg-block d-none card-load" data-map-view-target="listReviewCard" data-controller="review-card-item" data-action="mouseenter->review-card-item#mouseEnter mouseleave->review-card-item#mouseLeave" data-review-card-item-name-value="<%= review.name %>" data-review-card-item-latitude-value="<%= review.latitude %>" data-review-card-item-longitude-value="<%= review.longitude %>">
  <div class="card list-review">
    <div class="card-header col-2 p-0 border-0 position-relative" data-controller="favourite" data-favourite-liked-path-value="<%= review_update_favourite_path(review) %>">
      <%= link_to review_path(review.slug) do %>
        <% if review.images.present? %>
          <div data-controller= "carousel-loader" class="owl-carousel owl-theme card_carousel">
            <% review.images[..5].each do |image| %>
              <div class="item"><%= image_tag(image) %></div>
            <% end %>
          </div>
        <% else %>
          <div class="image-placeholder item"><%= image_tag("template/card-placeholder.svg") %></div>
        <% end %>
      <% end %>
      <span data-action="click->favourite#updateFavourite" data-fill-heart-icon="<%= asset_path("template/fill-heart.svg") %>" data-empty-heart-icon="<%= asset_path("template/empty_heart_white.svg") %>" class="favourite <%= 'checked' if review.favourite == true %>">
        <%= image_tag(review.favourite ? "template/fill-heart.svg" : "template/empty_heart_white.svg") %>
      </span>
    </div>
    <div class="card-body col-10">
      <div class="col-12">
        <div class="top">
          <div>
            <span class='review_btn'><%= review.to_try ? "Wishlist" : "Review" %> </span>
            <span class="share_btn"><%= image_tag(review.shareable ? "template/add.png" : "template/lock.svg") %></span>
          </div>
          <p class="product_rating"><%= image_tag("template/star.svg") if review.average_score? %>
            <span><%= review.average_score %></span></p>
        </div>
        <h3><%= review.name %></h3>
        <ul class="list_group">
          <% if review.city.present? %>
            <li><%= review.city %></li>
          <% end %>
          <% if review.state.present? and review.country.present? %>
            <li><%= "#{review.state}, #{ review.country}" %></li>
          <% end %>
          <% if !review.city.present? and !review.country.present? and review.date? %>
            <li>
              <%= review.date.strftime("%b %e, %Y") %>
            </li>
          <% end %>
          <li class="ml-1">
            <% if review.price_range.present? %>
              <% for count in 1..4 %>
                <span class="price-sz pe-none <%= ('text-white bg-price' if review.price_range >= count) %>">$</span>
              <% end %>
            <% end %>
          </li>
        </ul>
      </div>

      <!-- TODO:" Real data from google yelp and foursquare yet to fetch then had to use the following structure-->
      <%# if review.foursquare_url.present? || review.google_url.present? || review.yelp_url.present? %>
      <!--        <div class="col-7 url-list-view">-->
      <%# if review.foursquare_url.present? %>
      <!--            <div class="col-4 list-site-review">-->
      <%#= image_tag("template/Foursquare.svg") %>
      <!--              <p class="list-sites-reviews-numbers">4.6<span class="light-numbers"> / 5.0</span>-->
      <!--                <span class="small-numbers">409 reviews</span></p>-->
      <!--            </div>-->
      <%# end %>
      <%# if review.google_url.present? %>
      <!--            <div class="col-4 list-site-review">-->
      <%#= image_tag("template/Google.svg") %>
      <!--              <p class="list-sites-reviews-numbers">4.6<span class="light-numbers"> / 5.0</span>-->
      <!--                <span class="small-numbers">409 reviews</span></p>-->
      <!--            </div>-->
      <%# end %>
      <%# if review.yelp_url.present? %>
      <!--            <div class="col-4 list-site-review">-->
      <%#= image_tag("template/Yelp.svg") %>
      <!--              <p class="list-sites-reviews-numbers">4.6<span class="light-numbers"> / 5.0</span>-->
      <!--                <span class="small-numbers">409 reviews</span></p>-->
      <!--            </div>-->
      <%# end %>
      <!--        </div>-->
      <%# end %>

    </div>
  </div>
</div>

app/views/shared/_profile_image.html.erb
<div class="d-flex justify-content-center profile-img-wraper m-auto mt-5 position-relative">
  <%= image_tag(current_user.avatar.attached? ? current_user.avatar : "template/avatar_placeholder.jpg", class: 'rounded-circle') %>
  <%= link_to edit_user_registration_path, class: "rounded-circle avatar-edit" do %>
    <%= image_tag "template/edit.svg", class: "avatar-edit-icon" %>
  <% end %>
</div>

app/views/shared/_review_cards.turbo_stream.erb
<%= turbo_stream.append("groups-reviews") do %>
  <%= render partial: 'reviews/grid_review_card', collection: reviews, as: :review %>
<% end %>

<%= turbo_stream.append("list-groups-reviews") do %>
  <%= render partial: 'shared/list_review_card', collection: reviews, as: :review %>
<% end %>

<%= turbo_stream.update "next_link" do %>
  <% if @pagy.next.present? %>
    <%= link_to "Load More", pagy_url_for(pagy, pagy.next), id: 'loadMoreButton', 'data-turbo-stream': "true", class: "btn btn-primary #{'load-more' if params[:map].present?}" %>
  <% end %>
<% end %>

app/views/shared/_share_modal.html.erb
<!--Share Modal-->
<div class="modal fade" id="shareModal" tabindex="-1" aria-labelledby="shareModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="shareModalLabel">Share this review</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div id="share"></div>
      </div>
      <div class="modal-footer justify-content-center">
        <p class="link-field col-lg-7 col-12" data-guest-target="urlField"> hello </p>
        <button type="button" class="col-lg-4 col-12 btn white" data-action="click->guest#copyLink">Copy Link</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_show_header_title.html.erb
<h1><%= review.name %></h1>
<ul class="show-list-group">

  <% if review.sub_category_id.present? %>
    <li>
      <span class="show-subcategory"><%= review.sub_category.name %></span>
    </li>
  <% end %>
  <% if review.state.present? && review.country.present? %>
    <li>
      <span class="review-show-detail"><%= "#{review.state}, #{review.country}" %></span>
    </li>
  <% end %>
  <% if review.date.present? %>
    <li>
      <span class="review-show-detail"><%= review.date.strftime("%b %e, %Y") %></span>
    </li>
  <% end %>
  <% if review.price_range.present? %>
    <li>
  <span class="d-block d-lg-inline-block">
        <% for count in 1..4 %>
          <span class="price-sz pe-none show-price <%= ('text-white bg-price' if review.price_range >= count) %>">$</span>
        <% end %>
      </span>
  <% end %>
  </li>
</ul>