config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#index"
  apipie
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :guests, only: [:show]
  resources :categories, only: :index
  resources :requests, only: :create

  resources :reviews do
    delete :delete_attachment, on: :member
    get :update_favourite
    get :get_score
    get :update_status
  end

  scope :users do
    resources :groups, only: [:index, :create, :update, :destroy, :show] do
      post :show, on: :member
    end
  end
  get 'groups/search'
  get 'users/index'
  patch 'users/update'
  get 'users/remove_avatar'
  get 'users/delete_user'
  get 'users/settings'
  patch 'users/update'
  post 'upload', to: 'file_uploads#upload'
  patch :update_categories_status, to: 'categories#update_categories_status'
  get :homepage, to: 'reviews#homepage'
  get :edit_new, to: 'groups#edit_new'
  get :create_review, to: 'guests#create_review'
  get :show_map, to: 'reviews#show_map'
  post :homepage, to: 'reviews#homepage'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      mount_devise_token_auth_for "User", at: "/users", controllers: {
        sessions: "api/v1/sessions",
        passwords: "api/v1/passwords",
        registrations: "api/v1/registrations"
      }
      resources :reviews, only: [:create, :index, :update] do
        post :create_review_with_num
      end
      resources :groups, only: [:index, :create, :update, :destroy]
      resources :categories, only: :index
      resources :users, only: :update do
        post :change_password
      end
      resources :filters, only: :index
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord

  has_one_attached :icon
  has_many :reviews, dependent: :destroy
  has_many :sub_categories
end

app/controllers/api/v1/categories_controller.rb
module Api
  module V1
    class CategoriesController < Api::V1::ApiController
      api :GET, "categories", "Get a list of all available categories"

      example <<-EOS
        
      Status Codes with Response
      200: {
            "categories": [
              {
            "name": "Restaurants",
            "address": true,
            "icon": "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3745d7a2c3a1ea12155d58dc364affea8affc9b3/cutlery.svg",
            "google_places": true,
            "price": true,
            "cuisine": true,
            "active": true,
            "position": 1,
            "sub_category_title": "Genres",
            "start_date": null,
            "end_date": null,
            "author": null,
            "platform": null,
            "url": null,
            "google_url": null,
            "foursquare_url": null,
            "yelp_url": null,
            "created_at": "2022-08-23T10:16:26.562Z",
            "updated_at": "2022-12-14T12:43:26.245Z",
            "customized_fields": [
                "Location",
                "Name",
                "Cuisines",
                "Date",
                "Url",
                "Foursquare Url",
                "Yelp Url",
                "Score",
                "Price",
                "Description",
                "Photos",
                "Address",
                "City",
                "State",
                "Zip Code",
                "Country",
                "Tags",
                "Highlights"
            ],
            "sub_categories": [
                {
                    "id": 1,
                    "category_id": 1,
                    "name": "Action",
                    "created_at": "2022-09-28T09:06:18.299Z",
                    "updated_at": "2022-09-28T09:06:18.299Z"
                }
            ]
        }
          ]
      }
      EOS

      def index
        categories = Category.all.order(id: :asc)
        render json: categories, adapter: :json
      end

    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order(id: :asc)
  end
  def update_categories_status
    if update_category?
      redirect_to reviews_path, status: :see_other, notice: "Category updated successfully!"
    else
      redirect_to categories_path
    end
  end

  def update_category?
    params[:categories].each do |category|
      Category.find(category.first).update(active: category.second)
    end
    params[:positions].each do |position|
      Category.find(position.first).update(position: position.second)
    end
  end
end

app/views/categories/index.html.erb
<div class="manage-categories">
  <h3>
    All Categories
  </h3>
    <div class="active">
      <ul class="active-list category-list">
        <% @categories.each do |category| %>
          <% if category.active? %>
            <li class="drag-field category-list-item row">
              <span class="category-name col-9"><%= category.name %></span>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
</div>

<div class="manage-categories d-flex">
  <div class="col-8">
    <h3>
      Don’t see categories for you?
    </h3>
    <p class="request-catagory">Let us know about that. We constantly develop our app and we're looking for new
      solutions.</p>
  </div>
  <div class="col-4 m-auto">
    <button type="button" class="request-btn d-block ms-auto" data-bs-toggle="modal" data-bs-target="#request-modal">
      Send Request
    </button>

    <!-- Request Modal -->
    <div class="modal fade" id="request-modal" tabindex="-1" aria-labelledby="requestModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <%= form_for :request, url: requests_path, method: :post, html: {'data-turbo' => "false"} do |req_form| %>
            <div class="modal-header d-block">
              <div class="header-title d-flex align-items-center">
                <h2 class="modal-title" id="requestModalLabel">New Category Request</h2>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <p class="header-para">Tell us more about your needs. Enter the name of the new category and describe a
                bit
                your requirements.</p>
            </div>
            <div class="modal-body">
              <div class="mb-4 request">
                <%= req_form.label :name, "Your Name", class: "form-label" %>
                <%= req_form.text_field :name, class: "form-control", placeholder: "Enter your name", type: "text" %>
              </div>
              <div class="mb-4 request">
                <%= req_form.label :email, "Email", class: "form-label" %>
                <%= req_form.email_field :email, class: "form-control", placeholder: "Enter your email" %>
              </div>
              <div class="mb-4 request">
                <%= req_form.label :category_name, "Category Name", class: "form-label" %>
                <%= req_form.text_field :category_name, class: "form-control", placeholder: "Enter category name", type: "text" %>
              </div>
              <div class="mb-4 request">
                <%= req_form.label :description, "Category Description", class: "form-label" %>
                <%= req_form.text_area :description, class: "form-control", placeholder: "Describe your request about the new category...", type: "text", rows: 10 %>
              </div>
            </div>
            <div class="modal-footer justify-content-between">
              <button type="button" class="cancel" data-bs-dismiss="modal">Cancel</button>
              <%= req_form.submit "Send Request", class: 'save-changes' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>