config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#index"
  apipie
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :guests, only: [:show]
  resources :categories, only: :index
  resources :requests, only: :create

  resources :reviews do
    delete :delete_attachment, on: :member
    get :update_favourite
    get :get_score
    get :update_status
  end

  scope :users do
    resources :groups, only: [:index, :create, :update, :destroy, :show] do
      post :show, on: :member
    end
  end
  get 'groups/search'
  get 'users/index'
  patch 'users/update'
  get 'users/remove_avatar'
  get 'users/delete_user'
  get 'users/settings'
  patch 'users/update'
  post 'upload', to: 'file_uploads#upload'
  patch :update_categories_status, to: 'categories#update_categories_status'
  get :homepage, to: 'reviews#homepage'
  get :edit_new, to: 'groups#edit_new'
  get :create_review, to: 'guests#create_review'
  get :show_map, to: 'reviews#show_map'
  post :homepage, to: 'reviews#homepage'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      mount_devise_token_auth_for "User", at: "/users", controllers: {
        sessions: "api/v1/sessions",
        passwords: "api/v1/passwords",
        registrations: "api/v1/registrations"
      }
      resources :reviews, only: [:create, :index, :update] do
        post :create_review_with_num
      end
      resources :groups, only: [:index, :create, :update, :destroy]
      resources :categories, only: :index
      resources :users, only: :update do
        post :change_password
      end
      resources :filters, only: :index
    end
  end

end

app/controllers/api/v1/reviews_controller.rb
module Api
  module V1
    class ReviewsController < Api::V1::ApiController
      skip_before_action :authenticate_user!, only: [:create_review_with_num]
      before_action :validate_key, only: [:create_review_with_num]

      api :POST, "reviews", "Get a list of current user reviews or with applied filters"
      param :page, String, desc: "Page number of the reviews you want to get", required: false

      example <<-EOS
        
      Status Codes with Response
      200: {
    "reviews": [
        {
            "id": 84,
            "user_id": 1,
            "name": "KFC Yum! Center",
            "address": "1 Arena Plaza",
            "city": "Louisville",
            "state": "KY",
            "country": "United States",
            "place_id": "ChIJ8QWjWLxyaYgR5MYIpV71c0c",
            "longitude": "-85.7542438",
            "latitude": "38.25716789999999",
            "favorite_dish": null,
            "average_score": 5.0,
            "notes": "<p>Very good</p>",
            "date": "2022-11-15",
            "created_at": "2022-11-17T11:02:57.829Z",
            "updated_at": "2022-11-17T11:03:29.960Z",
            "zip_code": "40202-1363",
            "tags": ",hello,working",
            "price_range": 4,
            "status": null,
            "favourite": null,
            "shareable": true,
            "category_id": 1,
            "to_try": false,
            "discarded_at": null,
            "images": [
                "https://cdn.filestackcontent.com/WCxWynf7QX2NJDhXgjqv",
                "https://cdn.filestackcontent.com/2KIs4ADS4OrYQFOgUfQb"
            ],
            "parent_id": null,
            "slug": "U9GSBhCiaArmMmrsgAFqFUedzBhQU51p84",
            "start_date": null,
            "end_date": null,
            "author": null,
            "platform": null,
            "url": null,
            "google_url": null,
            "foursquare_url": "https://foursquare.com/v/antidote/4cab506a2f08236a745c8561",
            "yelp_url": null,
            "sub_category_name": "Afghan"
        }
        ],
        "meta": {
            "current_page": 1,
            "total_pages": 103
        }
    }

      EOS

      def index
        reviews = review_filter(current_user.reviews.includes(:sub_category, :meals))
        pagy, reviews = pagy(reviews)
        render json: reviews, meta: pagy_meta(pagy), each_serializer: ReviewSerializer, adapter: :json
      end

      api :POST, "reviews/create_review", "Create a new review"
      param :average_score, Integer, desc: "Should be between 1 to 10"
      param :price_range, Integer, desc: "Should be between 1 to 4"

      example <<-EOS
    {
        "id": 47,
        "user_id": 2,
        "name": "Arcadian Cafe",
        "address": "28 k Sir Syed Rd, Block K Gulberg 2, Lahore, Punjab, Pakistan",
        "city": "Lahore",
        "state": "Punjab",
        "country": "Pakistan",
        "place_id": "ChIJCfxBr_kEGTkR-1wlJ_OYM28",
        "longitude": "74.3493876",
        "latitude": "31.52254760000001",
        "favorite_dish": null,
        "average_score": 8.0,
        "notes": "sakdvbaskbdvkjasbdvckljasbdkjvcas.dkbcjsavdjchasd",
        "date": "2023-01-14",
        "created_at": "2022-09-15T11:13:51.514Z",
        "updated_at": "2023-01-12T15:20:46.683Z",
        "zip_code": "54646",
        "tags": [
            "tag 1",
            "tag 2"
        ],
        "price_range": 3,
        "status": null,
        "favourite": true,
        "shareable": true,
        "category_id": 1,
        "sub_category_id": null,
        "to_try": false,
        "discarded_at": null,
        "images": [
            "https://cdn.filestackcontent.com/jfx62MmZRmGcuWPFgUQh",
            "https://cdn.filestackcontent.com/iFWkHjXrTgGonIKj3U7f"
        ],
        "parent_id": null,
        "slug": "arcadian-cafe-47",
        "start_date": "2023-01-14",
        "end_date": "2023-01-17",
        "author": "Harry Potter",
        "platform": "",
        "url": "",
        "google_url": "",
        "foursquare_url": "",
        "yelp_url": "",
        "meals": [
            {
                "id": 40,
                "name": "Ywwwwwwes",
                "notes": "This is note 1",
                "image_url": "image_url",
                "created_at": "2022-12-28T10:45:31.151Z",
                "updated_at": "2023-01-12T13:59:47.243Z",
                "review_id": 47
            }
        ]
    }

      EOS

      def create_review
        review = current_user.reviews.new(review_params)
        if review.save
          render json: review, adapter: :json
        else
          render_error(422, review.errors.full_messages)
        end
      end

      api :PUT, "reviews/:id", "Update a review with an id"

      example <<-EOS
          {
              "name": "Arcadian Cafe",
              "category_id": "1",
              "sub_category_id": "",
              "to_try": "false",
              "shareable": "true",
              "date": "2023-01-14",
              "tags": ["tag 1", "tag 2"],
              "address": "28 k Sir Syed Rd, Block K Gulberg 2, Lahore, Punjab, Pakistan",
              "state": "Punjab",
              "city": "Lahore",
              "country": "Pakistan",
              "zip_code": "54646",
              "latitude": "31.52254760000001",
              "longitude": "74.3493876",
              "place_id": "ChIJCfxBr_kEGTkR-1wlJ_OYM28",
              "price_range": "3",
              "average_score": "8",
              "start_date": "2023-01-14",
              "end_date": "2023-01-17",
              "author": "Harry Potter",
              "platform": "",
              "url": "",
              "google_url": "",
              "foursquare_url": "",
              "yelp_url": "",
              "sub_category_name": "Afghan",
              "notes": "sakdvbaskbdvkjasbdvckljasbdkjvcas.dkbcjsavdjchasd",
              "images": [
                  "https://cdn.filestackcontent.com/jfx62MmZRmGcuWPFgUQh",
                  "https://cdn.filestackcontent.com/iFWkHjXrTgGonIKj3U7f"
              ],
              "meals_attributes": [
                  {
                      "id": "43",
                      "name": "Ywwwwwwes",
                      "notes": "This is note 1",
                      "image_url": "image_url",
                      "_destroy": "true"
                  }
              ]
          }
      EOS

      def update
        review = Review.find(params[:id])
        if review.update(review_params)
          render json: review, each_serializer: ReviewSerializer, adapter: :json
        else
          render_error(422, review.errors.full_messages)
        end
      end

      def create_review_with_num
        user = User.find_by(phone_number: params[:phone_number])
        rev_name = FetchTitleService.new(params[:review]['url'])
        if params[:phone_number].present? && user.present?
          review = user.reviews.new(name: rev_name.call, category_id: Category.find_by(name: "Others").id, to_try: true, url: params[:url])
          review.save ? message("#{request.env['rack.url_scheme']}://#{request.host_with_port}/reviews/#{review.slug}/edit") : review.errors.full_messages
        else
          message("check content type or user dose not exit with this phone number")
        end
      end

      private

      def validate_key
        message("invalid secret key") unless Rails.application.credentials.config[:x_api_key] == request.headers["x-api-key"]
      end

      def message(msg)
        render json: {
          message: msg
        }
      end

      def review_filter(reviews)
        reviews = reviews.where(category_id: params[:filters][:category_id]) if params[:filters][:category_id].present?
        reviews = reviews.where(to_try: params[:filters][:to_try]) if params[:filters][:to_try].present?
        reviews = reviews.where('tags ilike any (array[?])', params[:filters][:tags].map { |str| "%,#{str}%" }) if params[:filters][:tags].present?
        reviews = location_filter(reviews) if params[:filters][:location].present?
        reviews = reviews.ransack(name_or_state_or_city_or_country_or_tags_or_notes_or_sub_category_name_i_cont_any: params[:filters][:query]).result if params[:filters][:query].present?
        reviews = reviews.ransack(sub_category_name_i_cont_any: params[:filters][:sub_category_names]).result if params[:filters][:sub_category_names].present?
        reviews = if params[:filters][:order].present?
                    reviews.order(params[:filters][:order] == "recent" ? "created_at desc" : "average_score #{params[:filters][:order]} NULLS LAST")
                  else
                    reviews.order(Arel.sql("CASE WHEN date IS NOT NULL THEN date WHEN start_date IS NOT NULL THEN start_date ELSE reviews.created_at END")).reverse_order
                  end
        reviews
      end

      def location_filter(reviews)
        location_obj = {
          "cities": [],
          "states": [],
          "countries": []
        }
        params[:filters][:location].each do |obj|
          location_obj[:cities] << obj[:city] if obj[:city].present?
          location_obj[:states] << obj[:state] if obj[:state].present?
          location_obj[:countries] << obj[:country] if obj[:country].present?
        end
        reviews = reviews.where(state: location_obj[:states].uniq) if location_obj[:states].present?
        reviews = reviews.where(city: location_obj[:cities].uniq) if location_obj[:cities].present?
        reviews = reviews.where(country: location_obj[:countries].uniq) if location_obj[:countries].present?
        reviews
      end

      def review_params
        "<p>#{params[:review][:notes]}<p>" if params[:review][:notes].present?

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :filestack_image_uploader]
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :home_data, only: [:homepage, :index, :show_map]
  before_action :category_order, only: [:homepage, :new, :create, :edit]

  def homepage
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def index
    duplicate_review if session[:edit_review].present?
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def home_data
    if params[:category_id].present?
      @curr_category = params[:category_id] == "all" ? "all" : Category.find_by(id: params[:category_id])
    else
      @curr_category = "all"
    end
    reviews = review_filter(current_user.reviews)
    @pagy, @reviews = pagy_countless(reviews)
    @addresses = locations(@reviews)
  end

  def new
    @review = current_user.reviews.new
    @curr_category = params[:category_id].present? ? Category.find_by(id: params[:category_id]) : Category.find_by(name: 'Restaurants')
  end

  def create
    @review = current_user.reviews.new(review_params)
    if @review.save
      FetchUrlJob.perform_later(@review, params[:review][:city], params[:review][:name]) if params[:review][:city].present? && params[:review][:name].present?
      redirect_to root_path, status: :see_other, notice: "Review created successfully!"
    else
      @curr_category = params[:review][:category_id].present? ? Category.find_by(id: params[:review][:category_id]) : Category.find_by(name: 'Restaurants')
      render :new
    end
  end

  def duplicate_review
    edit_review = session[:edit_review]
    review_id = session[:review_id]
    session.delete(:review_id)
    session.delete(:edit_review)
    existing_review = Review.find_by(slug: review_id)
    new_review = existing_review.dup
    if new_review.update(user_id: current_user.id, parent_id: existing_review.id, slug: "#{SecureRandom.base58(32)}#{Review.last.id + 1}", to_try: edit_review == 'true' ? new_review.to_try : true)
      redirect_to edit_review == 'true' ? edit_review_path(new_review) : review_path(new_review.slug)
    else
      redirect_to reviews_path, notice: "Review didn't created successfully please try again"
    end
  end

  def show
    if current_user.blank? || current_user.reviews.find_by(slug: params[:id]).blank?
      redirect_to guest_path
      return
    end

    @review = current_user.reviews.find_by(slug: params[:id])
    @parent_id = @review.parent_id
    @review_user = User.find_by(id: @review.user_id)
  end

  def edit
    @curr_category = params[:category_id].present? ? Category.find(params[:category_id]) : @review.category
  end

  def update
    if @review.update(review_params)
      if params[:review][:deleted_meals].blank? || params[:review][:deleted_meals].present? && Meal.where(id: params[:review][:deleted_meals].split(',')).destroy_all
        redirect_to review_path(@review), notice: "Review updated successfully!"
      else
        redirect_to edit_review_path(@review), notice: "Meal did not deleted try again"
      end
    else
      render :new
    end
  end

  def destroy
    if @review.discard
      redirect_to current_user.second_view? ? homepage_path(format: :html) : reviews_path(format: :html), status: :see_other, notice: "Review deleted successfully!"
    end
  end

  def delete_attachment
    @image = ActiveStorage::Attachment.find(params[:attachment_id])
    @image.purge if @image.present?
  end

  def update_favourite
    Review.find_by(slug: params[:review_id]).update(favourite: params[:favourite])
  end

  def update_status
    Review.find_by(slug: params[:review_id]).update(shareable: params[:share])
  end

  def show_map
  end

  def category_order
    @ordered_categories = Category.all.order(id: :asc)
  end

  def get_score
    foursquare_yelp = FetchRatingsService.new(params[:foursquare_yelp_url])
    foursquare_yelp = foursquare_yelp.call
    render json: foursquare_yelp
  end

  def filestack_image_uploader
    user = User.confirm_by_token(params[:auth_token])
    if user.valid? && params[:images_url].blank?
      sign_in(user)
      user.update(confirmation_token: nil)
      @images = params[:review_id].present? ? Review.find(params[:review_id]).images : nil
      render "/mobile/filestack_view"
    else
      Review.find(params[:review_id]).update(images: params[:images_url])
      sign_out(user)
      redirect_to new_user_session_path
    end
  end

  private

  def set_review
    @review = current_user.reviews.find_by(slug: params[:id])
  end

  def review_params
    params[:review][:images] = [] if params[:review][:images] == [""]
    params.require(:review).permit(:name, :category_id, :to_try, :sub_category_id, :shareable, :date, :tags, :address, :state, :city, :country, :zip_code, :latitude, :longitude, :place_id, :favorite_dish, :price_range, :average_score, :start_date, :end_date, :author, :platform, :url, :google_url, :foursquare_url, :yelp_url, :notes, images: [], meals_attributes: [:id, :name, :notes, :image_url, :_destroy])
  end

  def locations(reviews)
    reviews.map do |review|
      if review.city.present? && review.state.present?
        "#{review.city} . #{review.state}"
      elsif review.state.present?
        review.state
      elsif review.city.present?
        review.city
      else
        ''
      end
    end.uniq.reject(&:empty?).sort
  end
end

app/views/reviews/_favourite_dishes.html.erb
<h2>Highlights</h2>
<div class="tabs_content_wrap" data-controller="meals" data-meals-edit-icon-value="<%= asset_path('template/pen.png') %>" data-meals-delete-icon-value="<%= asset_path('template/delete.svg') %>">
  <div class="favourite_dishes_tab_wrap text-center">
    <ul class="favorite_dishes_list" data-meals-target="favouriteMeals">
      <div class="<%= "d-none" if f.object.meals.present? %> " data-meals-target="noMealDiv">
        <h2>No Highlights yet</h2>
        <div>Add your Highlights</div>
      </div>
      <%= f.hidden_field :deleted_meals, value: "", 'data-meals-target': "deletedMeals"%>
      <% index = 0 %>
      <%= f.fields_for :meals do |meal_form| %>
        <li data-meals-target="mealCard" id="<%= index %>">
          <img id="image-<%= index %>" class='main_img' src='<%= meal_form.object.image_url %>'>
          <%= meal_form.hidden_field :image_url %>
          <%= meal_form.hidden_field :name %>
          <%= meal_form.hidden_field :notes %>
          <%= meal_form.hidden_field :_destroy %>
          <div class='d-flex justify-content-between align-items-center w-100 ml_15'>
            <div class="text-left">
              <h4 id="name-<%= index %>"> <%= meal_form.object.name %></h4>
              <p id="notes-<%= index %>"><%= meal_form.object.notes %>...</p>
            </div>
            <span class="cursor-pointer">
            <span id="<%= index %>" data-action="click->meals#editMeal">
                <%= image_tag('template/pen.png') %>
            </span>
            <span>
              <%= image_tag("template/delete.svg", id: "#{index}", "data-action": "click->meals#deleteMeal", class: "h-17") %>
            </span>
        </span>
          </div>
        </li>
        <% index += 1 %>
      <% end %>
    </ul>
    <!-- Button trigger modal -->
    <button type="button" data-action="click->meals#resetModal" class="btn white mt-4" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <span class="icon">+</span><span>Highlight</span>
    </button>
  </div>

  <!-- Modal -->
  <div class="modal fade meal-modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-focus="false">
    <div class="modal-dialog modal-container" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 data-meals-target="modalLabel" class="modal-title h2" id="exampleModalLabel">Add meal</h5>
          <button type="button" class="btn-close close" data-bs-dismiss="modal" aria-label="Close">
          </button>
        </div>

        <div class="modal-body">
          <div class="image-container position-relative">
            <%= f.filestack_field :images_input, 'Upload File', class: 'thumbnail px-0 position-absolute', id: 'unique-iddd', input_id: 'unique-input-idsd', pickerOptions: { onFileUploadFinished: 'callbackOnFileUploadFinished1' } %>
            <img id='meal-photo' data-meals-target="image" src=''>
          </div>

          <div class="form-group row align-items-center mb-3">
            <label for="name" class="col-sm-4 col-form-label">Meal Name</label>
            <div class="col-sm-8">
              <input type="text" class="form-control-plaintext input-field" id="mealName" placeholder="Enter name" data-meals-target="mealName">
            </div>
          </div>

          <div class="form-group row">
            <label for="staticEmail" class="col-sm-4 col-form-label">Notes</label>
            <div class="col-sm-8">
              <textarea type="text" class="form-control-plaintext" id="mealNotes" data-meals-target="mealNotes"></textarea>
            </div>
          </div>
        </div>

        <div class="d-flex justify-content-between modal-footer">
          <button type="button" class="btn white" data-bs-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal" data-meals-target="mealId" data-action="click->meals#saveChanges">Save
            changes
          </button>
        </div>
      </div>
    </div>
  </div>

  <script>
    function callbackOnFileUploadFinished1(data) {
      document.getElementById('meal-photo').src = data.url;
    }
  </script>
</div>

app/views/reviews/_owner_show_header.html.erb
<div class="row align-items-end pb_50">
  <div class="col-lg-6">
    <div class="public_review" data-controller="favourite" data-favourite-status-path-value="<%= review_update_status_path(review) %>">
      <div class="mode-switch d-flex flex-row align-items-center">
        <input type="checkbox" id="switch" <%= 'checked' if review.shareable? %> data-favourite-target="publicStatus">
        <label for="switch" data-action="click->favourite#updateReviewStatus"></label>
      </div>
      <%= image_tag("template/users.svg", class: 'mr_5') %>
      <span>Public REVIEW</span>
    </div>
    <%= render "shared/show_header_title", review: review %>
  </div>
  <div class="col-lg-6 text-end d-none d-lg-block">
    <div class="d-flex align-items-center justify-content-end avatar">
      <div>
        <p class="reviewer">Reviewer</p>
        <p class="name"><%= current_user.username %></p>
      </div>
      <span class="show-user-img">
         <%= image_tag(review_user.avatar.attached? ? review_user.avatar : "template/avatar_placeholder.jpg") %>
      </span>
    </div>
    <div class="d-flex align-items-center justify-content-end rating_box" data-controller="favourite" data-favourite-liked-path-value="<%= review_update_favourite_path(review) %>">
      <span data-action="click->favourite#updateFavourite" data-fill-heart-icon="<%= asset_path("template/fill-heart.svg") %>" data-empty-heart-icon="<%= asset_path("template/empty-heart.svg") %>" class=<%= "#{'checked' if review.favourite} #{ 'm-0' if review.average_score.blank?}" %>>
        <% unless current_user.second_view? %>
          <%= image_tag(review.favourite ? "template/fill-heart.svg" : "template/empty-heart.svg" ) %>
          <span class="faveroit <%= review.favourite ? "" : 'text-black-50' %>">Save as Favorite</span>
        <% end %>
      </span>
      <% if review.average_score.present? %>
        <p class="rating">
          <%= image_tag("template/star.svg") %><span><%= review.average_score %></span></p>
      <% end %>
    </div>
    <div class="review-url d-flex justify-content-end mb-4">
      <%= link_to @review.url.truncate(32, separator: ' '), @review.url, class: "review-link", target: '_blank' if @review.url.present? %>
    </div>
    <div>
      <button class="btn white <%= 'text-black-50 border-secondary' if review.shareable != true %>" <%= 'disabled' if review.shareable != true %> type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#shareModal" data-action="click->guest#addLinkField">
        <%= image_tag("template/share.svg") %>Share
      </button>
      <%= link_to edit_review_path(review), class: 'btn' do %>
        <%= image_tag("template/edit-fill.svg") %><span>Edit</span>
      <% end %>
    </div>
  </div>
  <!-- for mobile -->
  <div class="col-12 d-lg-none">
    <div class="d-flex justify-content-between align-items-center pt_30">
      <div class="d-flex align-items-center avatar">
        <span class="show-user-img">
        <%= image_tag(review_user.avatar.attached? ? review_user.avatar : "template/avatar_placeholder.jpg") %>
        </span>
        <div class="pl_10">
          <p class="reviewer">Reviewer</p>
          <p class="name"><%= current_user.username %></p>
        </div>
      </div>
      <div class="rating_box">
        <% if review.average_score.present? %>
          <p class="rating"><%= image_tag("template/star.svg") %>
            <span><%= review.average_score %></span></p>
        <% end %>
      </div>
    </div>
    <div class="review-url d-flex justify-content-end mb-4">
      <%= link_to @review.url.truncate(32, separator: ' '), @review.url, class: "review-link", target: '_blank' if @review.url.present? %>
    </div>
    <div class="d-flex justify-content-between pt_30">
      <button class="btn white <%= 'text-black-50 border-secondary' if review.shareable != true %>" <%= 'disabled' if review.shareable != true %> type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#shareModal" data-action="click->guest#addLinkField">
        <%= image_tag("template/share.svg") %>Share
      </button>
      <%= link_to edit_review_path(review), class: 'btn' do %>
        <%= image_tag("template/edit-fill.svg") %><span>Edit</span>
      <% end %>
    </div>
  </div>
  <!-- mobile end-->
  <%= render "shared/share_modal" %>
</div>

app/views/reviews/_resturant_card.html.erb
<!-- single card -->
<div class="col-lg-3 col-md-6">
  <div class="card">
    <div class="card-header p-0 border-0 position-relative">
      <% if review.images.present? %>
        <div class="owl-carousel owl-theme card_carousel">
          <% review.images.each do |image| %>
            <div class="item"><%= image_tag(image) %></div>
          <% end %>
        </div>
        <button class="favourite"><%= image_tag("template/favourites.png") %></button>
        <% else %>
        <div class="image-placeholder item"><%= image_tag("template/placeholder-image.webp") %></div>
      <% end %>
    </div>
    <div class="card-body">
      <div class="top">
        <div>
          <%= link_to "Review", review_path(review), class: 'review_btn' %>
          <a class="share_btn" href="#"><%= review.shareable ? image_tag("template/add.png") : image_tag("template/lock.svg") %></a>
        </div>
        <p class="product_rating"><%= image_tag("template/star.png") if review.average_score? %><span><%= review.average_score %></span></p>
      </div>
      <h3><%= review.name %></h3>
      <ul class="list_group">
        <li><%= review.city %></li>
        <li><%= review.state %>, <%= review.country %></li>
        <li class="ml-1"><span>$</span><span>$</span><span>$</span><span>$</span></li>
      </ul>
    </div>
  </div>
</div>

app/views/reviews/_review_card.html.erb
<!-- single card -->
<div class="col-lg-3 col-md-6 card-load">
  <div class="card review-card">
    <div class="card-header p-0 border-0 position-relative" data-controller="favourite" data-favourite-favourite-path-value="<%= review_update_favourite_path(review) %>">
      <% if review.images.present? %>
        <%= link_to review_path(review.slug) do %>
          <div class="owl-carousel owl-theme card_carousel">
            <% review.images[..5].each do |image| %>
              <div class="item"><%= image_tag(image) %></div>
            <% end %>
          </div>
        <% end %>
        <span data-action="click->favourite#updateFavourite" class="favourite <%= 'checked' if review.favourite == true %>"><%= image_tag(review.favourite ? "template/fill-heart.svg" : "template/empty-heart.svg") %></span>
      <% else %>
        <%= link_to review_path(review.slug) do %>
          <div class="image-placeholder item"><%= image_tag("template/card-placeholder.svg") %></div>
        <% end %>
        <span data-action="click->favourite#updateFavourite" class="favourite <%= 'checked' if review.favourite == true %>"><%= image_tag(review.favourite ? "template/fill-heart.svg" : "template/empty-heart.svg") %></span>
      <% end %>
    </div>
    <div class="card-body">
      <div class="top">
        <div>
          <span class='review_btn'><%= review.to_try ? "Wishlist" : "Review" %> </span>
          <span class="share_btn"><%= image_tag(review.shareable ? "template/add.png" : "template/lock.svg") %></span>
        </div>
        <p class="product_rating"><%= image_tag("template/star.svg") if review.average_score? %>
          <span><%= review.average_score %></span></p>
      </div>
      <h3><%= review.name %></h3>
      <ul class="list_group">
        <% if review.city.present? %>
          <li><%= review.city %></li>
        <% end %>
        <% if review.state.present? and review.country.present? %>
          <li><%= review.state %> <%= ',' + review.country %></li>
        <% end %>
        <% if !review.city.present? and !review.country.present? and review.date? %>
          <li>
            <%= review.date.strftime("%b %e, %Y") %>
          </li>
        <% end %>
        <li class="ml-1">
          <% for count in 1..4 %>
            <span class="price-sz pe-none <%= ('text-white bg-price' if review.price_range >= count) if review.price_range.present? %>">$</span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/reviews/edit.html.erb
<%= render "shared/form", review: @review, head_name: "Edit"  %>

app/views/reviews/homepage.turbo_stream.erb
<%= render 'new_homepage/review_cards', reviews: @reviews, pagy: @pagy %>